Added method for cross bi-directional trust attack
Semperis/GoldenGMSA pull request #6
Opened 2022-03-04 13:41 UTC by MartinSohn

I have added a trust attack technique with GoldenGMSA to the code and readme. I also fixed a few things in the readme.

Please see attached PDF for details and demonstrations:
[GoldenGMSA trust attack.pdf](https://github.com/Semperis/GoldenGMSA/files/8186241/GoldenGMSA.trust.attack.pdf)

2022-03-05 17:27 UTC, GuyTe requested changes

2022-03-05 17:27 UTC, GuyTe commented on GoldenGMSA/Program.cs
This cancels the offline mode and tries to talk to AD even when all the required arguments have been passed on the command line (sid/KdsRootKeyBase64/ManagedPwdIdBase64). Offline mode does not require the domain/forest names.

2022-03-31 17:23 UTC, Quazaka approved these changes

2022-03-31 17:29 UTC, MartinSohn reviewed
Hi Guy, thank you for the fix, can you merge into master?

2022-04-05 21:08 UTC, GuyTe commented
> Hi Guy, thank you for the fix, can you merge into master?

I don't see how you have addresses the point I
 have raised. The function should be able to operate in "offline" mode when all the required arguments have been provided (i.e.: both KdsRootKeyBase64 and ManagedPwdIdBase64 have been passed as arguments). In this scenario no AD calls are required and rest of the arguments should be ignored

2022-04-06 09:13 UTC, MartinSohn commented
I gotcha @GuyTe, please have a look at the newest commit.
Here I query both domains for info and compute online:
![image](https://user-images.githubusercontent.com/2473497/161940278-bc962107-bb44-4a02-a8df-b5989b09a073.png)

Here I compute offline by giving previously returned values:
![image](https://user-images.githubusercontent.com/2473497/161940626-8672935d-6bed-4249-b7c8-cc17a37eb584.png)

2022-04-06 13:55 UTC, GuyTe approved these changes

2022-04-06 13:56 UTC, merged

2022-04-06 13:57 UTC, GuyTe commented
Thanks @MartinSohn for the additions and the cleanup. Much appreciated

2023-02-24 20:17 UTC, jsdhasfedssad commented
Thank you for PR which I will surely use in future. Is there any way to convert the base64 encoded password to an NT hash? This would open up for a lot more tools.

I have decoded the base64 encoded password using different methods but they all end up in an unusable state.